<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\..\Common\Common.Application\Common.Application.csproj" />
    <ProjectReference Include="..\..\Projects\Projects.Contracts\Projects.Contracts.csproj" />
    <ProjectReference Include="..\..\Users\Users.Contracts\Users.Contracts.csproj" />
  </ItemGroup>

</Project>

