FROM mcr.microsoft.com/dotnet/sdk:10.0 AS build
WORKDIR /app

COPY *.sln ./

COPY src/Common/Common.Domain/Common.Domain.csproj ./src/Common/Common.Domain/
COPY src/Common/Common.Application/Common.Application.csproj ./src/Common/Common.Application/
COPY src/Common/Common.Infrastructure/Common.Infrastructure.csproj ./src/Common/Common.Infrastructure/

COPY src/Modules/Tenants/Tenants.Domain/Tenants.Domain.csproj ./src/Modules/Tenants/Tenants.Domain/
COPY src/Modules/Tenants/Tenants.Application/Tenants.Application.csproj ./src/Modules/Tenants/Tenants.Application/
COPY src/Modules/Tenants/Tenants.Infrastructure/Tenants.Infrastructure.csproj ./src/Modules/Tenants/Tenants.Infrastructure/
COPY src/Modules/Tenants/Tenants.Api/Tenants.Api.csproj ./src/Modules/Tenants/Tenants.Api/

COPY src/Modules/Users/Users.Domain/Users.Domain.csproj ./src/Modules/Users/Users.Domain/

COPY src/Modules/Contracts/Contracts.csproj ./src/Modules/Contracts/

RUN dotnet restore ./src/Modules/Tenants/Tenants.Api/Tenants.Api.csproj

COPY . .

WORKDIR /app/src/Modules/Tenants/Tenants.Api
RUN dotnet publish --no-restore -c Release -o /app/publish /p:UseAppHost=false

FROM mcr.microsoft.com/dotnet/aspnet:10.0 AS final

WORKDIR /app
EXPOSE 8080

COPY --from=build /app/publish .

ENTRYPOINT ["dotnet", "Tenants.Api.dll"]